# Generated by Django 3.0.3 on 2020-03-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('albumArt', models.URLField()),
                ('upvotes', models.IntegerField(default=0)),
                ('artist', models.CharField(max_length=128)),
            ],
        ),
    ]
