# Generated by Django 3.0.3 on 2020-03-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spuni', '0002_auto_20200308_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(),
        ),
    ]
