# Generated by Django 3.0.3 on 2020-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spuni', '0006_userprofile_upvotedsongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='upvotedSongs',
            field=models.ManyToManyField(blank=True, related_name='user_song', to='spuni.Song'),
        ),
    ]
