# Generated by Django 3.0.3 on 2020-04-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spuni', '0008_auto_20200329_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='downvotedSongs',
            field=models.ManyToManyField(blank=True, related_name='downvoted_song', to='spuni.Song'),
        ),
    ]
